source 'https://github.com/CocoaPods/Specs.git'

target 'SoundManager_Example' do
  pod 'SoundManager', :path => '../'
  pod 'iOS-Slide-Menu', '~> 1.4.5'
end

target 'SoundManager_Tests' do
  pod 'SoundManager', :path => '../'
end
